name: Build and Push to ECR

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push WebApp image
        run: |
          docker build -t clo835-webapp -f Dockerfile .
          docker tag clo835-webapp:latest 767398033131.dkr.ecr.us-east-1.amazonaws.com/clo835-webapp:latest
          docker push 767398033131.dkr.ecr.us-east-1.amazonaws.com/clo835-webapp:latest

      - name: Build, tag, and push MySQL image
        run: |
          docker build -t clo835-mysql -f Dockerfile_mysql .
          docker tag clo835-mysql:latest 767398033131.dkr.ecr.us-east-1.amazonaws.com/clo835-mysql:latest
          docker push 767398033131.dkr.ecr.us-east-1.amazonaws.com/clo835-mysql:latest
